function movies = importmovies(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MOVIES = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  MOVIES = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  movies = importfile("C:\Users\JAYASURYAMARASANI\OneDrive - Amrita university\Desktop\AIE A\SEMESTER 2\19MAT117 Maths 2\Maths Project\MathsProject\ml-1m\movies.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jul-2021 02:28:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["MovieID", "MovieName", "Var3", "Var4"];
opts.SelectedVariableNames = ["MovieID", "MovieName"];
opts.VariableTypes = ["double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["MovieName", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["MovieName", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
movies = readtable(filename, opts);

end