function ratings = ratingsimport(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RATINGS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  RATINGS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ratings = importfile("C:\Users\karth\OneDrive\Desktop\New folder\ratings.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jul-2021 03:19:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "::";

% Specify column names and types
opts.VariableNames = ["UserID", "MovieID", "Ratings", "TimeStamp"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ratings = readtable(filename, opts);

end